config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registration => "registration"}
  get 'home/index'

  resources :posts

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# Ability class manages user authorization
class Ability
  include CanCan::Ability
  def initialize(user)
    # from cancan community, knowledge purpose only
    can :read, :all# permissions for every user, even if not logged in    
    if user.present?  # additional permissions for logged in users (they can manage their posts)
      can :manage, Post, user_id: user.id 
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
    # Define abilities for the passed in user here. For example:
    #

    # if !user
    #   if user.nil?
    #     can :read, :all
    #   else
    #     if user.role.admin?
    #       can :manage, :all
    #     elseif user.role.app_user?# === "app_user" #if user.role === User.ROLadminES[admin]
    #       can :read, :all
    #     end
    #   end
    # end

    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :pictures, as: :imageable
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/shopping_bag.rb
class ShoppingBag < ApplicationRecord
end

app/models/user.rb
# User class used to manage application users
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:admin, :app_user, :designer, :banned, :editor, :photographer, :guest]
  has_one :user

  after_create :build_user

  def build_user
    User.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_url, :alert => exception.message
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
# Post class is responsible for creating posts
class PostsController < ApplicationController
    load_and_authorize_resource
    def index
        @posts = Post.all
    end

    def create
        @post =  Post.new(post_params)
        @post.save
        redirect_to @post
    end

    def show
        @post = Post.find(params[:id])
    end

    private
        def post_params
            params.require(:post).permit(:title, :text)
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Products
    end

    def show
        @product = Products.find(product_params)
    end

    def edit
        @product = Products.find(params[:id])
    end

    def create
        @product =  Products.new(product_params)
        @product.save
        redirect_to @product
    end

    private
        def product_params
            params.require(:product).permit(:name, :price)
        end
end

app/controllers/registration_controller.rb
class Devise::RegistrationController < DeviseController
    # extend Devise::Models
    before_action :configure_permitted_parameters, :only => [:create]

    def new
    end
    def edit
    end
    def update
    end
    def delete
    end
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |usr|
                usr.permit(:email,
                    :password,
                    :role)
            }
        end

    private
        def user_params
            params.require(:user).permit(:email, :password)
        end
end

app/controllers/shopping_bag_controller.rb
class ShoppingBagController < ApplicationController
end

app/controllers/user_controller.rb
class User < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @user = User
    end

    def show
        @user = User.find(user_params)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:id, :name, :summary, :birthday)
    end
end

app/controllers/users_controller.rb
class Users < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @user = User
    end

    def show
        @user = User.find(user_params)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:id, :name, :summary, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/shopping_bag_helper.rb
module ShoppingBagHelper
end

app/views/home/index.html.erb
<div class="nav-home">
    <h1 class="home nav-bar">Home</h1>
    <h2 class="home-welcome">Welcome to LeSuave</h2>
    <h3 class="home-header">Have class, have style, le suave</h3>
    <div class="link">
        <%= link_to 'View Posts', controller: 'posts' %>
    </div>
    <br>
    <div class="posts">
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.text %></td>
                <td><%= link_to 'Show', post_path(post) %></td>
            </tr>
        <% end %> 
    </div>
</div>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
 
<%= link_to 'New Post', new_post_path %>
<div class="post">
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
    </tr>
  
  <% @posts.each do |post| %>
      <tr>
          <td><%= post.title %></td>
          <td><%= post.text %></td>
          <td><%= link_to 'Show', post_path(post) %></td>
      </tr>
  <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :text %> <br>
        <%= form.text_area :text %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @post.text %>
</p>

app/views/shopping_bag/edit.html.erb
<%
=begin%>
 <%= simple_form_for @product do |prdct| %>
  <%= prdct.name :name %>
  <%= prdct.price :price %>
  <%= prdct.quantity :quantity %>
  <%= prdct.button :submit, 'Save', class: 'submit' %>
 <% end %> 
<%
=end%>

app/views/shopping_bag/index.html.erb
<%
=begin%>
 
<h1>Your bag</h1>

<div class="shopping_bag">
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
    </tr>
  
  <% @shoppingbag.each do |item| %>
      <tr>
          <td><%= item.name %></td>
          <td><%= item.preview %></td>
          <td><%= item.short_description %></td>
          <td><%= link_to 'Show', post_path(item) %></td>
      </tr>
      <tr>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
      <tr/>
  <% end %>
  </table>
  <button>Bag the bag</button>
</div> 
<%
=end%>

app/views/user/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.date_select :birthday %>
  <%= f.text_field :summary %>
  <%= f.button :submit, 'Save', class: 'submit' %>
 <% end %>